version: '3.0'

services:
    app:
        image: node:16.5
        ports:
            - "4200:4200"
        volumes:
            - ./:/app
        working_dir: /app
        entrypoint: tail -f "/dev/null"
