version: '3.0'


services:
    webserver:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./app.conf:/etc/nginx/conf.d/app.conf
            - .:/var/www
