export const abilities = [
  // Attack
  "Slice",
  "Backhand",
  "Lesser Smash",
  "Lesser Havoc",
  "Lesser Sever",
  "Slaughter",
  "Overpower",
  "Havoc",
  "Forceful Backhand",
  "Smash",
  "Barge",
  "Greater Barge",
  "Flurry",
  "Greater Flurry",
  "Sever",
  "Hurricane",
  "Bladed Dive",
  "Massacre",
  "Blood Tendrils",
  "Meteor Strike",
  "Balanced Strike",

  // Strength
  "Lesser Dismember",
  "Kick",
  "Stomp",
  "Punish",
  "Dismember",
  "Greater Fury",
  "Fury",
  "Destroy",
  "Quake",
  "Berserk",
  "Cleave",
  "Assault",
  "Decimate",
  "Pulverise",
  "Frenzy",
  "Chaos Roar",

  // Magic
  "Wrack",
  "Impact",
  "Asphyxiate",
  "Lesser Combust",
  "Lesser Dragon Breath",
  "Lesser Sonic Wave",
  "Lesser Concentrated Blast",
  "Wrack and Ruin",
  "Omnipower",
  "Deep Impact",
  "Dragon Breath",
  "Sonic Wave",
  "Shock",
  "Concentrated Blast",
  "Greater Concentrated Blast",
  "Horror",
  "Combust",
  "Detonate",
  "Chain",
  "Greater Chain",
  "Wild Magic",
  "Golden Touch",
  "Metamorphosis",
  "Magma Tempest",
  "Magma Tempest (Targeted)",
  "Corruption Blast",
  "Smoke Tendrils",
  "Greater Sonic Wave",
  "Tsunami",
  "Sunshine",
  "Greater Sunshine",

  // Ranged
  "Piercing Shot",
  "Binding Shot",
  "Snap Shot",
  "Lesser Dazing Shot",
  "Lesser Needle Strike",
  "Lesser Fragmentation Shot",
  "Lesser Snipe",
  "Quiver ammo slot 1",
  "Quiver ammo slot 2",
  "Deadshot",
  "Tight Bindings",
  "Snipe",
  "Dazing Shot",
  "Greater Dazing Shot",
  "Demoralise",
  "Needle Strike",
  "Rout",
  "Fragmentation Shot",
  "Rapid Fire",
  "Ricochet",
  "Greater Ricochet",
  "Bombardment",
  "Salt the Wound",
  "Incendiary Shot",
  "Corruption Shot",
  "Shadow Tendrils",
  "Unload",
  "Death's Swiftness",
  "Greater Death's Swiftness",

  // Defence
  "Aggression",
  "Unsullied",
  "Cease",
  "Devotion",
  "Anticipation",
  "Bash",
  "Revenge",
  "Provoke",
  "Immortality",
  "Freedom",
  "Reflect",
  "Resonance",
  "Divert",
  "Rejuvenate",
  "Debilitate",
  "Preparation",
  "Barricade",
  "Natural Instinct",

  // Constitution
  "Eat Food",
  "Weapon Special Attack",
  "Regenerate",
  "Sacrifice",
  "Transfigure",
  "Ingenuity of the Humans",
  "Limitless",
  "Slayer's Insight",
  "Kuradal's Favour",
  "Dragon Slayer",
  "Demon Slayer",
  "Undead Slayer",
  "Essence of Finality",
  "Siphon",
  "Incite",
  "Tuska's Wrath",
  "Storm Shards",
  "Shatter",
  "Reprisal",
  "Guthix's Blessing",
  "Onslaught",
  "Ice Asylum",

  // Agility
  "Surge",
  "Escape",
  "Dive",
];
